"""Initial commit.

Revision ID: ae09eecd4854
Revises: 115d8e3a7632
Create Date: 2023-05-09 12:11:32.721032

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ae09eecd4854"
down_revision = "115d8e3a7632"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("uuid", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_players_uuid"), "players", ["uuid"], unique=False)
    op.add_column("questions", sa.Column("type_", sa.String(length=16), nullable=False))
    op.drop_column("questions", "type")
    op.add_column("rounds", sa.Column("type_", sa.String(length=16), nullable=False))
    op.drop_column("rounds", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rounds", sa.Column("type", sa.VARCHAR(length=16), autoincrement=False, nullable=False)
    )
    op.drop_column("rounds", "type_")
    op.add_column(
        "questions", sa.Column("type", sa.VARCHAR(length=16), autoincrement=False, nullable=False)
    )
    op.drop_column("questions", "type_")
    op.drop_index(op.f("ix_players_uuid"), table_name="players")
    op.drop_column("players", "uuid")
    # ### end Alembic commands ###
