"""Initial commit.

Revision ID: 115d8e3a7632
Revises: 81d2bf64dc3f
Create Date: 2023-05-08 17:20:53.802032

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "115d8e3a7632"
down_revision = "81d2bf64dc3f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_games_uuid"), "games", ["uuid"], unique=False)
    op.create_index(op.f("ix_packages_uuid"), "packages", ["uuid"], unique=False)
    op.create_index(op.f("ix_questions_uuid"), "questions", ["uuid"], unique=False)
    op.create_index(op.f("ix_rounds_uuid"), "rounds", ["uuid"], unique=False)
    op.create_index(op.f("ix_topics_uuid"), "topics", ["uuid"], unique=False)
    op.create_index(op.f("ix_users_uuid"), "users", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_uuid"), table_name="users")
    op.drop_index(op.f("ix_topics_uuid"), table_name="topics")
    op.drop_index(op.f("ix_rounds_uuid"), table_name="rounds")
    op.drop_index(op.f("ix_questions_uuid"), table_name="questions")
    op.drop_index(op.f("ix_packages_uuid"), table_name="packages")
    op.drop_index(op.f("ix_games_uuid"), table_name="games")
    # ### end Alembic commands ###
