"""Initial second commit.

Revision ID: 504326e6180c
Revises: e709cb02ee81
Create Date: 2023-05-08 10:36:18.800376

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "504326e6180c"
down_revision = "e709cb02ee81"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("user_uuid", sa.Uuid(), nullable=False),
        sa.Column("game_uuid", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["game_uuid"], ["games.uuid"]),
        sa.ForeignKeyConstraint(["user_uuid"], ["users.uuid"]),
        sa.PrimaryKeyConstraint("user_uuid", "game_uuid"),
    )
    op.create_table(
        "rounds",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("game_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["game_uuid"], ["games.uuid"]),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "topics",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("round_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["round_uuid"], ["rounds.uuid"]),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "questions",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("text", sa.String(length=1024), nullable=False),
        sa.Column("answer", sa.String(length=128), nullable=False),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("file_path", sa.String(length=128), nullable=True),
        sa.Column("topic_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["topic_uuid"], ["topics.uuid"]),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.add_column("games", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.add_column("games", sa.Column("started_at", sa.DateTime(timezone=True), nullable=False))
    op.add_column("games", sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False))
    op.add_column("packages", sa.Column("title", sa.String(length=64), nullable=False))
    op.add_column("packages", sa.Column("difficult", sa.Integer(), nullable=False))
    op.add_column("packages", sa.Column("rating", sa.Integer(), nullable=False))
    op.add_column("packages", sa.Column("counter", sa.Integer(), nullable=False))
    op.add_column("packages", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.add_column("packages", sa.Column("author_uuid", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "packages", "users", ["author_uuid"], ["uuid"])
    op.add_column("users", sa.Column("nickname", sa.String(length=32), nullable=False))
    op.add_column("users", sa.Column("password_hash", sa.String(length=128), nullable=False))
    op.add_column("users", sa.Column("email", sa.String(length=128), nullable=False))
    op.add_column("users", sa.Column("file_path", sa.String(length=128), nullable=True))
    op.add_column("users", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.add_column("users", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("users", "file_path")
    op.drop_column("users", "email")
    op.drop_column("users", "password_hash")
    op.drop_column("users", "nickname")
    op.drop_constraint(None, "packages", type_="foreignkey")
    op.drop_column("packages", "author_uuid")
    op.drop_column("packages", "created_at")
    op.drop_column("packages", "counter")
    op.drop_column("packages", "rating")
    op.drop_column("packages", "difficult")
    op.drop_column("packages", "title")
    op.drop_column("games", "finished_at")
    op.drop_column("games", "started_at")
    op.drop_column("games", "created_at")
    op.drop_table("questions")
    op.drop_table("topics")
    op.drop_table("rounds")
    op.drop_table("players")
    # ### end Alembic commands ###
