"""Initial commit.

Revision ID: e709cb02ee81
Revises: 
Create Date: 2023-05-06 22:13:55.739849

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e709cb02ee81"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "packages", sa.Column("uuid", sa.Uuid(), nullable=False), sa.PrimaryKeyConstraint("uuid")
    )
    op.create_table(
        "users", sa.Column("uuid", sa.Uuid(), nullable=False), sa.PrimaryKeyConstraint("uuid")
    )
    op.create_table(
        "games",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("CREATED", "STARTED", "PAUSED", "FINISHED", name="gamestatus"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("presenter_uuid", sa.Uuid(), nullable=False),
        sa.Column("package_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["package_uuid"], ["packages.uuid"]),
        sa.ForeignKeyConstraint(["presenter_uuid"], ["users.uuid"]),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("games")
    op.drop_table("users")
    op.drop_table("packages")
    # ### end Alembic commands ###
