"""Initial commit.

Revision ID: b15df6bec5ae
Revises: 
Create Date: 2023-05-06 19:33:06.030428

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b15df6bec5ae"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "packages",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "users",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "games",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_paused", sa.Boolean(), nullable=False),
        sa.Column("is_finished", sa.Boolean(), nullable=False),
        sa.Column("presenter_uuid", sa.String(length=36), nullable=False),
        sa.Column("package_uuid", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["package_uuid"], ["packages.uuid"]),
        sa.ForeignKeyConstraint(["presenter_uuid"], ["users.uuid"]),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("games")
    op.drop_table("users")
    op.drop_table("packages")
    # ### end Alembic commands ###
